from typing import Dict, List, Optional

from .schemas import Platform, ProductOut


EUR_TO_RON = 4.97
VAT_RO = 0.19
DUTY: Dict[str, float] = {
    "8518300000": 0.00,
    "3926909090": 0.065,
    "9405409090": 0.044,
    "8471300000": 0.00,
    "6110200000": 0.12,
}
FREIGHT = {"air": 5.8, "sea_lcl": 1.2, "sea_fcl": 0.38}
BROKER_FEE = 95.0
WAREHOUSE_FEE = 120.0


CATALOG: Dict[str, List[ProductOut]] = {
    "casti wireless": [
        ProductOut(
            id=1,
            platform="alibaba",
            name="Căști TWS BT5.3 ANC Premium",
            supplier="Shenzhen AudioTech Co., Ltd.",
            price_eur=7.80,
            moq=500,
            lead_days=15,
            rating=4.8,
            reviews=2841,
            verified=True,
            audited=True,
            ta=True,
            kg=0.09,
            hs="8518300000",
            cat="Electronice",
            img="🎧",
        ),
        ProductOut(
            id=2,
            platform="alibaba",
            name="Căști OEM IPX5 Waterproof Custom Logo",
            supplier="Guangzhou SoundPro Electronics",
            price_eur=4.90,
            moq=1000,
            lead_days=20,
            rating=4.5,
            reviews=1203,
            verified=True,
            audited=False,
            ta=True,
            kg=0.08,
            hs="8518300000",
            cat="Electronice",
            img="🎧",
        ),
        ProductOut(
            id=3,
            platform="aliexpress",
            name="Căști Sport Wireless V5.0 Bass",
            supplier="TechStore Official",
            price_eur=11.20,
            moq=1,
            lead_days=7,
            rating=4.6,
            reviews=18420,
            verified=False,
            audited=False,
            ta=False,
            kg=0.10,
            hs="8518300000",
            cat="Electronice",
            img="🎧",
        ),
        ProductOut(
            id=4,
            platform="alibaba",
            name="Căști ANC Factory Direct ODM/OEM",
            supplier="Dongguan Hengli Electronics",
            price_eur=3.90,
            moq=2000,
            lead_days=25,
            rating=4.3,
            reviews=445,
            verified=True,
            audited=True,
            ta=True,
            kg=0.08,
            hs="8518300000",
            cat="Electronice",
            img="🎧",
        ),
    ],
    "huse telefon": [
        ProductOut(
            id=5,
            platform="alibaba",
            name="Husă TPU iPhone 15 Custom Print",
            supplier="Shenzhen CaseMaster Co.",
            price_eur=1.10,
            moq=500,
            lead_days=10,
            rating=4.9,
            reviews=5621,
            verified=True,
            audited=True,
            ta=True,
            kg=0.04,
            hs="3926909090",
            cat="Accesorii",
            img="📱",
        ),
        ProductOut(
            id=6,
            platform="alibaba",
            name="Husă Piele Wallet OEM Multi-model",
            supplier="Guangzhou LeatherTech",
            price_eur=2.60,
            moq=300,
            lead_days=14,
            rating=4.6,
            reviews=2103,
            verified=True,
            audited=False,
            ta=True,
            kg=0.06,
            hs="3926909090",
            cat="Accesorii",
            img="📱",
        ),
        ProductOut(
            id=7,
            platform="aliexpress",
            name="Husă Clear Shockproof Universal",
            supplier="Phone Accessories Hub",
            price_eur=1.95,
            moq=1,
            lead_days=6,
            rating=4.4,
            reviews=34100,
            verified=False,
            audited=False,
            ta=False,
            kg=0.05,
            hs="3926909090",
            cat="Accesorii",
            img="📱",
        ),
    ],
    "becuri led": [
        ProductOut(
            id=8,
            platform="alibaba",
            name="Bandă LED RGB 5M 12V SMD5050",
            supplier="Shenzhen LightWorld Co.",
            price_eur=3.40,
            moq=200,
            lead_days=12,
            rating=4.7,
            reviews=3240,
            verified=True,
            audited=True,
            ta=True,
            kg=0.15,
            hs="9405409090",
            cat="Iluminat",
            img="💡",
        ),
        ProductOut(
            id=9,
            platform="aliexpress",
            name="Bec Smart WiFi E27 10W Tuya",
            supplier="BrightHome Store",
            price_eur=4.60,
            moq=1,
            lead_days=8,
            rating=4.5,
            reviews=12800,
            verified=False,
            audited=False,
            ta=False,
            kg=0.12,
            hs="9405409090",
            cat="Iluminat",
            img="💡",
        ),
    ],
    "laptop": [
        ProductOut(
            id=10,
            platform="alibaba",
            name='Laptop 15.6" Intel i5 8GB 256GB SSD',
            supplier="Shenzhen ComputerPro Ltd.",
            price_eur=185.0,
            moq=50,
            lead_days=18,
            rating=4.6,
            reviews=820,
            verified=True,
            audited=True,
            ta=True,
            kg=1.8,
            hs="8471300000",
            cat="IT",
            img="💻",
        ),
        ProductOut(
            id=11,
            platform="aliexpress",
            name='Laptop Gaming 15.6" Ryzen 5 16GB',
            supplier="TechMall Official",
            price_eur=310.0,
            moq=1,
            lead_days=10,
            rating=4.4,
            reviews=3210,
            verified=False,
            audited=False,
            ta=False,
            kg=2.1,
            hs="8471300000",
            cat="IT",
            img="💻",
        ),
    ],
    "tricouri": [
        ProductOut(
            id=12,
            platform="alibaba",
            name="Tricou Bumbac 100% Unisex Custom Print",
            supplier="Guangzhou Fashion Co.",
            price_eur=2.20,
            moq=300,
            lead_days=16,
            rating=4.5,
            reviews=4100,
            verified=True,
            audited=False,
            ta=True,
            kg=0.18,
            hs="6110200000",
            cat="Textile",
            img="👕",
        ),
        ProductOut(
            id=13,
            platform="aliexpress",
            name="Tricou Polo Sport Dry-Fit",
            supplier="SportWear Store",
            price_eur=3.80,
            moq=1,
            lead_days=7,
            rating=4.3,
            reviews=9800,
            verified=False,
            audited=False,
            ta=False,
            kg=0.20,
            hs="6110200000",
            cat="Textile",
            img="👕",
        ),
    ],
}


def find_product_by_id(product_id: int) -> Optional[ProductOut]:
    for items in CATALOG.values():
        for p in items:
            if p.id == product_id:
                return p
    return None

